// src/features/partner/components/PartnerAuth.tsx
import WebLayout from "@/components/layout/WebLayout"; // Import WebLayout
import { FC, useState } from "react";
import { useForm } from "react-hook-form";
import { z } from "zod";
import { zodResolver } from "@hookform/resolvers/zod";
import { cn } from "@/lib/utils";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Button } from "@/components/ui/button";
import { useAuth } from "../auth/AuthContext";
import { usePartnerNotification } from "../hooks/usePartnerNotification";

interface PartnerAuthProps {
  onLoginSuccess?: () => void;
}

const loginSchema = z.object({
  email: z.string().email("Please enter a valid email."),
  password: z.string().min(6, "Password must be at least 6 characters long."),
});

type LoginFormInputs = z.infer<typeof loginSchema>;

export const PartnerAuth: FC<PartnerAuthProps> = ({ onLoginSuccess }) => {
  const [isLoading, setIsLoading] = useState(false);
  const { login } = useAuth();
  const { showError, showSuccess } = usePartnerNotification();

  const {
    register,
    handleSubmit,
    formState: { errors, isValid, touchedFields },
  } = useForm<LoginFormInputs>({
    resolver: zodResolver(loginSchema),
    mode: "onTouched",
  });

  const onSubmit = async (data: LoginFormInputs) => {
    setIsLoading(true);
    console.log("PartnerAuth: onSubmit called. Form valid:", isValid);

    const result = await login({ email: data.email, password: data.password });

    if (result.success) {
      console.log("PartnerAuth: Login successful, emitting onLoginSuccess.");
      showSuccess("Login successful!");
      onLoginSuccess?.();
    } else {
      showError(result.error || "Login failed. Please check your credentials.");
      console.error("PartnerAuth: Login failed with error:", result.error);
    }
    setIsLoading(false);
  };

  return (
    <WebLayout>
      <div className="flex min-h-screen items-center justify-center">
        <div className="w-full max-w-md rounded-lg bg-background p-10 shadow-lg text-center">
          <h2 className="mb-5 text-2xl font-bold text-primary">Partner Login</h2>
          <p className="mb-6 text-muted-foreground">
            Please log in to access the video survey dashboard.
          </p>

          <form onSubmit={handleSubmit(onSubmit)} className="space-y-4">
            <div className="space-y-2 text-left">
              <Label htmlFor="email">Email</Label>
              <Input
                id="email"
                type="email"
                placeholder="Enter your email"
                {...register("email")}
                className={cn({ "border-destructive focus-visible:ring-destructive": errors.email && touchedFields.email })}
              />
              {errors.email && touchedFields.email && (
                <p className="text-sm text-destructive">{errors.email.message}</p>
              )}
            </div>

            <div className="space-y-2 text-left">
              <Label htmlFor="password">Password</Label>
              <Input
                id="password"
                type="password"
                placeholder="Enter your password"
                {...register("password")}
                className={cn({ "border-destructive focus-visible:ring-destructive": errors.password && touchedFields.password })}
              />
              {errors.password && touchedFields.password && (
                <p className="text-sm text-destructive">{errors.password.message}</p>
              )}
            </div>

            <Button type="submit" className="mt-6 w-full" disabled={!isValid || isLoading}>
              {isLoading && (
                <span
                  className="mr-2 h-4 w-4 animate-spin rounded-full border-2 border-primary-foreground border-r-transparent"
                  role="status"
                  aria-hidden="true"
                ></span>
              )}
              Login
            </Button>
          </form>
        </div>
      </div>
    </WebLayout>
  );
};

// _legacyFunctionality/partner/partner-auth/partner-auth.component.ts
import { Component, EventEmitter, Output } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule, ReactiveFormsModule, FormBuilder, FormGroup, Validators } from '@angular/forms';
import { AuthService } from '../services/auth.service';
import { NotificationService } from '../services/notification.service'; // Import NotificationService

@Component({
  selector: 'app-partner-auth',
  standalone: true,
  imports: [CommonModule, FormsModule, ReactiveFormsModule],
  templateUrl: './partner-auth.component.html',
  styleUrl: './partner-auth.component.scss',
})
export class PartnerAuthComponent {
  @Output() loggedIn = new EventEmitter<void>();
  loginForm: FormGroup;
  isLoading: boolean = false;

  constructor(
    private fb: FormBuilder,
    private authService: AuthService,
    private notificationService: NotificationService // Inject NotificationService
  ) {
    this.loginForm = this.fb.group({
      email: ['', [Validators.required, Validators.email]],
      password: ['', [Validators.required, Validators.minLength(6)]],
    });
    console.log('PartnerAuthComponent: Initialized login form.');
  }

  async onSubmit() {
    this.isLoading = true;
    console.log('PartnerAuthComponent: onSubmit called. Form valid:', this.loginForm.valid);

    if (this.loginForm.valid) {
      const { email, password } = this.loginForm.value;
      const result = await this.authService.login({ email, password });

      if (result.success) {
        console.log('PartnerAuthComponent: Login successful, emitting loggedIn.');
        this.notificationService.showSuccess('Login successful!');
        this.loggedIn.emit();
      } else {
        this.notificationService.showError(result.error || 'Login failed. Please check your credentials.');
        console.error('PartnerAuthComponent: Login failed with error:', result.error);
      }
    } else {
      this.notificationService.showError('Please enter valid email and password.');
      console.error('PartnerAuthComponent: Form is invalid.');
    }
    this.isLoading = false;
  }
}

<div class="auth-container">
  <div class="login-card">
    <h2>Partner Login</h2>
    <p>Please log in to access the video survey dashboard.</p>

    <form [formGroup]="loginForm" (ngSubmit)="onSubmit()">
      <div class="form-group">
        <label for="email">Email</label>
        <input
          id="email"
          type="email"
          formControlName="email"
          placeholder="Enter your email"
          [class.is-invalid]="loginForm.get('email')?.invalid && loginForm.get('email')?.touched"
        />
        <div
          *ngIf="loginForm.get('email')?.invalid && loginForm.get('email')?.touched"
          class="invalid-feedback"
        >
          <div *ngIf="loginForm.get('email')?.errors?.['required']">Email is required.</div>
          <div *ngIf="loginForm.get('email')?.errors?.['email']">Please enter a valid email.</div>
        </div>
      </div>

      <div class="form-group">
        <label for="password">Password</label>
        <input
          id="password"
          type="password"
          formControlName="password"
          placeholder="Enter your password"
          [class.is-invalid]="loginForm.get('password')?.invalid && loginForm.get('password')?.touched"
        />
        <div
          *ngIf="loginForm.get('password')?.invalid && loginForm.get('password')?.touched"
          class="invalid-feedback"
        >
          <div *ngIf="loginForm.get('password')?.errors?.['required']">Password is required.</div>
          <div *ngIf="loginForm.get('password')?.errors?.['minlength']">
            Password must be at least 6 characters long.
          </div>
        </div>
      </div>

      <button type="submit" class="login-button" [disabled]="loginForm.invalid || isLoading">
        <span *ngIf="isLoading" class="spinner-border spinner-border-sm" role="status" aria-hidden="true"></span>
        Login
      </button>
    </form>
  </div>
</div>
