// src/features/partner/components/PartnerDashboard.tsx
import React, { FC, useState, useEffect, useRef, useCallback } from "react";
import { format } from "date-fns";
import { cn } from "@/lib/utils";
import { useAuth } from "../auth/AuthContext";
import { usePartnerNotification } from "../hooks/usePartnerNotification";
import { uploadService } from "../services/uploadService";
import { DigitalManifestModal } from "./DigitalManifestModal";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Button } from "@/components/ui/button";
import { Link } from "react-router-dom";
import zeeroniLogo from "@/assets/zeeroni-logo.png";
import WebLayout from "@/components/layout/WebLayout"; // Ensure this is imported once at the top
import {
  SurveyUpload,
  GeminiAnalyzedItem,
  UploadStatus,
} from "../types"; // Assuming these types are defined

interface PartnerDashboardProps {}

// Extended SurveyUpload type to include client-side properties
interface ClientSurveyUpload extends SurveyUpload {
  progress: number;
  videoName: string;
}

const MAX_FILE_SIZE_MB = 40; // Max upload limit

export const PartnerDashboard: FC<PartnerDashboardProps> = () => {
  const { logout: authLogout } = useAuth();
  const { showSuccess, showError, showInfo } = usePartnerNotification();
  const {
    getPresignedUrl,
    uploadFileToS3,
    processUpload,
    getUserUploads,
    getUploadStatus,
    getDigitalManifest,
  } = uploadService();

  const fileUploadInputRef = useRef<HTMLInputElement>(null);
  const cameraInputRef = useRef<HTMLInputElement>(null);

  const [uploads, setUploads] = useState<ClientSurveyUpload[]>([]);
  const [isModalOpen, setIsModalOpen] = useState(false);
  const [selectedManifest, setSelectedManifest] = useState<
    GeminiAnalyzedItem[] | null
  >(null);
  const [isLoadingUploads, setIsLoadingUploads] = useState(false);
  const [isLoadingManifest, setIsLoadingManifest] = useState(false);

  // Upload flow states
  const [selectedFile, setSelectedFile] = useState<File | null>(null);
  const [filePreviewUrl, setFilePreviewUrl] = useState<string | null>(null);
  const [customFileName, setCustomFileName] = useState("");
  const [isUploading, setIsUploading] = useState(false);
  const [uploadProgress, setUploadProgress] = useState(0);
  const [uploadStatusMessage, setUploadStatusMessage] = useState("");

  // Polling state
  const uploadsToPoll = useRef<string[]>([]);
  const pollingIntervalRef = useRef<number | null>(null);

  const fetchUploads = useCallback(async () => {
    setIsLoadingUploads(true);
    try {
      const apiUploads: SurveyUpload[] = await getUserUploads();
      const newUploadsToPoll: string[] = [];
      const formattedUploads = apiUploads.map((apiUpload) => {
        const id = apiUpload.uploadId;
        const shortId = id.length > 8 ? `${id.slice(0, 4)}...${id.slice(-4)}` : id;
        if (
          apiUpload.status === "Pending" ||
          apiUpload.status === "Processing" ||
          apiUpload.status === "Queued"
        ) {
          newUploadsToPoll.push(apiUpload.uploadId);
        }
        return {
          ...apiUpload,
          progress:
            apiUpload.status === "Completed" || apiUpload.status === "Failed"
              ? 100
              : 0,
          videoName: apiUpload.fileName || `Video_${shortId}.mp4`,
        };
      });
      setUploads(formattedUploads);
      uploadsToPoll.current = newUploadsToPoll;
    } catch (error: any) {
      showError(error.message || "Failed to fetch uploads.");
    } finally {
      setIsLoadingUploads(false);
    }
  }, [getUserUploads, showError]);

  const pollUploadsStatus = useCallback(async () => {
    if (uploadsToPoll.current.length === 0) return;

    uploadsToPoll.current.forEach(async (uploadId) => {
      try {
        const apiUpload = await getUploadStatus(uploadId);
        setUploads((prevUploads) =>
          prevUploads.map((u) => {
            if (u.uploadId === apiUpload.uploadId && u.status !== apiUpload.status) {
              if (apiUpload.status === "Completed" || apiUpload.status === "Failed") {
                uploadsToPoll.current = uploadsToPoll.current.filter(
                  (id) => id !== uploadId,
                );
                showInfo(
                  `Upload status for ${apiUpload.fileName || u.videoName} is now ${apiUpload.status}.`,
                );
              }
              return { ...u, status: apiUpload.status, message: apiUpload.message };
            }
            return u;
          }),
        );
      } catch (error) {
        console.error(`Error polling status for ${uploadId}:`, error);
      }
    });
  }, [getUploadStatus, showInfo]);

  useEffect(() => {
    fetchUploads();
    // Start polling
    pollingIntervalRef.current = window.setInterval(pollUploadsStatus, 5000);

    return () => {
      // Cleanup polling on unmount
      if (pollingIntervalRef.current) {
        clearInterval(pollingIntervalRef.current);
      }
    };
  }, [fetchUploads, pollUploadsStatus]);

  const logout = useCallback(() => {
    authLogout();
    showInfo("You have been logged out.");
  }, [authLogout, showInfo]);

  const onFileSelected = useCallback(
    (event: React.ChangeEvent<HTMLInputElement>) => {
      const file = event.target.files?.[0];
      if (!file) return;

      if (file.type !== "video/mp4" && file.type !== "video/quicktime") {
        showError("Invalid file type. Only .mp4 and .mov files are accepted.");
        clearFileInput(event.target);
        return;
      }

      const maxSizeBytes = MAX_FILE_SIZE_MB * 1024 * 1024;
      if (file.size > maxSizeBytes) {
        showError(
          `File size exceeds the maximum limit of ${MAX_FILE_SIZE_MB}MB.`,
        );
        clearFileInput(event.target);
        return;
      }

      setSelectedFile(file);
      setCustomFileName(file.name.split(".").slice(0, -1).join(".")); // Remove extension
      setFilePreviewUrl(URL.createObjectURL(file));
    },
    [showError],
  );

  const clearFileInput = (input: HTMLInputElement | null) => {
    if (input) {
      input.value = "";
    }
  };

  const cancelSelection = useCallback(() => {
    setSelectedFile(null);
    setFilePreviewUrl(null);
    setCustomFileName("");
    setIsUploading(false);
    setUploadProgress(0);
    setUploadStatusMessage("");
    // Clear the value of the file input fields
    if (fileUploadInputRef.current) clearFileInput(fileUploadInputRef.current);
    if (cameraInputRef.current) clearFileInput(cameraInputRef.current);
  }, []);

  const retryUpload = useCallback(
    async (uploadId: string) => {
      const upload = uploads.find((u) => u.uploadId === uploadId);
      if (!upload) {
        showError("Could not find the upload to retry.");
        return;
      }

      setUploads((prev) =>
        prev.map((u) =>
          u.uploadId === uploadId
            ? { ...u, status: "Pending", message: "Retrying processing..." }
            : u,
        ),
      );

      try {
        const response = await processUpload(uploadId);
        showSuccess(`Retry initiated for ${upload.videoName}.`);
        setUploads((prev) =>
          prev.map((u) =>
            u.uploadId === uploadId
              ? { ...u, status: response.status, message: response.message }
              : u,
          ),
        );
        if (
          (response.status === "Pending" ||
            response.status === "Processing" ||
            response.status === "Queued") &&
          !uploadsToPoll.current.includes(uploadId)
        ) {
          uploadsToPoll.current.push(uploadId);
        }
      } catch (error: any) {
        console.error(`Retry failed for ${uploadId}:`, error);
        showError(error.message || "Retry failed: Unknown error");
        setUploads((prev) =>
          prev.map((u) =>
            u.uploadId === uploadId
              ? { ...u, status: "Failed", message: error.message || "Retry failed: Unknown error" }
              : u,
          ),
        );
      }
    },
    [uploads, processUpload, showError, showSuccess],
  );

  const onUpload = useCallback(async () => {
    if (!selectedFile || !customFileName) {
      showError("Please select a file and provide a file name.");
      return;
    }

    setIsUploading(true);
    setUploadProgress(0);
    setUploadStatusMessage("Requesting upload URL...");

    let finalFileName = customFileName;
    if (!customFileName.includes(".")) {
      const fileExtension =
        selectedFile.type === "video/quicktime" ? ".mov" : ".mp4";
      finalFileName = `${customFileName}${fileExtension}`;
    }

    try {
      const presignedResponse = await getPresignedUrl(
        finalFileName,
        selectedFile.type,
      );
      setUploadStatusMessage("Uploading video to secure storage...");

      await uploadFileToS3(presignedResponse.preSignedUrl, selectedFile, (progress) => {
        setUploadProgress(Math.round(progress));
      });

      setUploadProgress(100);
      setUploadStatusMessage("Finalizing upload...");

      await processUpload(presignedResponse.uploadId);

      showSuccess("Upload successful! Your video is now being processed.");
      cancelSelection();
      fetchUploads();
    } catch (error: any) {
      console.error("Upload failed:", error);
      showError(error.message || "Upload failed: Unknown error");
    } finally {
      setIsUploading(false);
    }
  }, [
    selectedFile,
    customFileName,
    showError,
    showSuccess,
    getPresignedUrl,
    uploadFileToS3,
    processUpload,
    cancelSelection,
    fetchUploads,
  ]);

  const getStatusClass = useCallback((status: UploadStatus): string => {
    switch (status) {
      case "Pending":
      case "Processing":
        return "bg-accent text-accent-foreground"; // Reusing accent for these statuses
      case "Queued":
        return "bg-blue-500 text-white"; // Using a specific blue for queued
      case "Completed":
        return "bg-primary text-primary-foreground";
      case "Failed":
        return "bg-destructive text-destructive-foreground";
      default:
        return "";
    }
  }, []);

  const openDigitalManifest = useCallback(
    async (uploadId: string) => {
      setIsLoadingManifest(true);
      try {
        const manifest = await getDigitalManifest(uploadId);
        setSelectedManifest(manifest);
        setIsModalOpen(true);
      } catch (error: any) {
        showError(error.message || "Failed to fetch digital manifest.");
      } finally {
        setIsLoadingManifest(false);
      }
    },
    [getDigitalManifest, showError],
  );

  const closeDigitalManifest = useCallback(() => {
    setIsModalOpen(false);
    setSelectedManifest(null);
  }, []);

  return (
    <WebLayout> {/* Use WebLayout to include the shared Header */}
      <div className="mx-auto w-full max-w-6xl flex-grow p-6">
        <h2 className="mb-4 text-center text-3xl font-bold text-primary">
          Video Survey
        </h2>
        <p className="mx-auto mb-8 max-w-xl text-center text-muted-foreground">
          Upload a video of your household items to generate a comprehensive{" "}
          <b>digital manifest</b>.
          <br />
          Simply select a video file or record directly from your device.
        </p>

        {/* Upload Options Area */}
        <div className="mb-8 flex flex-wrap justify-center gap-5">
          <div
            className="flex min-w-[280px] flex-1 cursor-pointer flex-col items-center justify-center rounded-lg border-2 border-dashed border-border bg-card p-8 transition-all hover:border-primary hover:shadow-lg"
            onClick={() => fileUploadInputRef.current?.click()}
          >
            <input
              type="file"
              ref={fileUploadInputRef}
              onChange={onFileSelected}
              hidden
              accept="video/*"
            />
            <p className="text-lg font-bold text-foreground">
              Upload a video file
            </p>
            <p className="mt-1 text-sm text-muted-foreground">
              Only small files less than {MAX_FILE_SIZE_MB}MB are supported
            </p>
          </div>

          <div
            className="flex min-w-[280px] flex-1 cursor-pointer flex-col items-center justify-center rounded-lg border-2 border-dashed border-border bg-card p-8 transition-all hover:border-primary hover:shadow-lg"
            onClick={() => cameraInputRef.current?.click()}
          >
            <input
              type="file"
              ref={cameraInputRef}
              onChange={onFileSelected}
              hidden
              accept="video/*"
              capture="environment"
            />
            <p className="text-lg font-bold text-foreground">Record directly</p>
            <p className="mt-1 text-sm text-muted-foreground">
              Set your camera settings to a lower resolution (30 FPS, 480p-720p)
            </p>
          </div>
        </div>

        {/* New Upload Preview and Confirmation Section */}
        {selectedFile && (
          <div className="mb-8 rounded-lg border bg-card p-6 shadow-md">
            <h4 className="mb-6 text-center text-xl font-bold text-primary">
              Upload Confirmation
            </h4>
            <div className="flex flex-wrap gap-6">
              <div className="flex-1 min-w-[300px]">
                <video src={filePreviewUrl || ""} controls className="w-full rounded-md bg-black"></video>
              </div>
              <div className="flex flex-1 flex-col justify-center">
                <div className="mb-5">
                  <Label htmlFor="customFileName" className="mb-2 block font-bold text-foreground">
                    File Name
                  </Label>
                  <Input
                    id="customFileName"
                    type="text"
                    value={customFileName}
                    onChange={(e) => setCustomFileName(e.target.value)}
                    placeholder="Enter a custom name for your video"
                    disabled={isUploading}
                    className="w-full p-3 text-base"
                  />
                </div>
                <div className="flex gap-3">
                  <Button
                    className="flex-1 p-3 text-base font-bold bg-primary hover:bg-primary/90 text-primary-foreground"
                    onClick={onUpload}
                    disabled={isUploading || !customFileName}
                  >
                    {isUploading ? (
                      <>
                        <span className="mr-2 h-4 w-4 animate-spin rounded-full border-2 border-primary-foreground border-r-transparent" />
                        Uploading...
                      </>
                    ) : (
                      "Confirm & Upload"
                    )}
                  </Button>
                  <Button
                    variant="secondary"
                    className="flex-1 p-3 text-base font-bold bg-muted hover:bg-muted/80 text-muted-foreground"
                    onClick={cancelSelection}
                    disabled={isUploading}
                  >
                    Cancel
                  </Button>
                </div>
              </div>
            </div>
            {/* Upload Status with Spinner */}
            {isUploading && (
              <div className="mt-6">
                <p className="mb-2 text-center font-bold text-foreground">
                  {uploadStatusMessage}
                  <span className="ml-2 inline-block h-3 w-3 animate-spin rounded-full border-2 border-foreground border-r-transparent" />
                </p>
                <div className="h-3 w-full rounded-full bg-secondary">
                  <div
                    className="h-full rounded-full bg-primary transition-all duration-400 ease-in-out"
                    style={{ width: `${uploadProgress}%` }}
                  ></div>
                </div>
              </div>
            )}
          </div>
        )}

        {/* Survey List */}
        <div className="rounded-lg bg-card p-6 shadow-md">
          <h3 className="mb-5 border-b pb-3 text-xl font-bold text-primary">
            Recent Uploads
          </h3>
          {isLoadingUploads ? (
            <div className="flex flex-col items-center justify-center p-10 text-primary">
              <div className="h-12 w-12 animate-spin rounded-full border-4 border-primary border-r-transparent" />
              <p className="mt-4 text-lg font-bold">Loading uploads...</p>
            </div>
          ) : (
            <>
              {uploads.length === 0 ? (
                <p className="p-5 text-center text-muted-foreground">
                  No uploads yet.
                </p>
              ) : (
                uploads.map((upload) => (
                  <div
                    key={upload.uploadId}
                    className="flex flex-wrap items-center justify-between gap-3 border-b py-4 last:border-b-0"
                  >
                    <div className="flex-1">
                      <span className="font-bold text-foreground">
                        {upload.fileName || upload.videoName}
                      </span>
                      <span className="ml-2 text-xs text-muted-foreground">
                        {format(new Date(upload.createdTimestamp), "MMM d, yyyy h:mm a")}
                      </span>
                    </div>
                    <div className="flex flex-col items-start min-w-[120px]">
                      {upload.status !== "Completed" && (
                        <span
                          className={cn(
                            "rounded-md px-2 py-1 text-xs font-bold uppercase",
                            getStatusClass(upload.status),
                          )}
                        >
                          {upload.status}
                          {(upload.status === "Pending" ||
                            upload.status === "Processing" ||
                            upload.status === "Queued") && (
                              <span className="ml-2 inline-block h-3 w-3 animate-spin rounded-full border-2 border-current border-r-transparent" />
                            )}
                        </span>
                      )}
                    </div>
                    <div className="flex gap-2">
                      {upload.status === "Completed" && (
                        <Button
                          onClick={() => openDigitalManifest(upload.uploadId)}
                          className="bg-primary hover:bg-primary/90 text-primary-foreground text-sm"
                          disabled={isLoadingManifest}
                        >
                          {isLoadingManifest ? (
                            <>
                              <span className="mr-2 h-4 w-4 animate-spin rounded-full border-2 border-primary-foreground border-r-transparent" />
                              Loading...
                            </>
                          ) : (
                            'Get Digital Manifest'
                          )}
                        </Button>
                      )}
                      {upload.status === "Failed" && (
                        <Button
                          onClick={() => retryUpload(upload.uploadId)}
                          className="bg-accent hover:bg-accent/90 text-white text-sm"
                        >
                          Retry
                        </Button>
                      )}
                    </div>
                  </div>
                ))
              )}
            </>
          )}
        </div>
      </div> {/* This div closes the content that was inside main */}

      <DigitalManifestModal
        manifestData={selectedManifest}
        isLoading={isLoadingManifest}
        isOpen={isModalOpen}
        onClose={closeDigitalManifest}
      />
    </WebLayout>
  );
};

// _legacyFunctionality/partner/partner-dashboard/partner-dashboard.component.ts
import { Component, OnInit, OnDestroy, ViewChild, ElementRef } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { HttpClient, HttpHeaders, HttpEventType } from '@angular/common/http';
import { DomSanitizer, SafeResourceUrl } from '@angular/platform-browser';
import { DigitalManifestModalComponent } from '../digital-manifest-modal/digital-manifest-modal.component';
import { AuthService } from '../services/auth.service';
import { NotificationService } from '../services/notification.service';
import { UploadService, PresignedUrlResponse } from '../services/upload.service';
import { SurveyUpload, GeminiAnalyzedItem } from '../shared/models';
import { interval, Subscription, switchMap, startWith, tap, catchError, of, finalize, EMPTY } from 'rxjs';
import { environment } from '../../../environments/environment';

@Component({
  selector: 'app-partner-dashboard',
  standalone: true,
  imports: [CommonModule, DigitalManifestModalComponent, FormsModule],
  templateUrl: './partner-dashboard.component.html',
  styleUrls: ['./partner-dashboard.component.scss'],
  providers: [UploadService] // Provide UploadService here
})
export class PartnerDashboardComponent implements OnInit, OnDestroy {
  @ViewChild('fileUploadInput') fileUploadInput!: ElementRef;
  @ViewChild('cameraInput') cameraInput!: ElementRef;
  // Existing properties
  uploads: (SurveyUpload & { progress: number; videoName: string })[] = [];
  isModalOpen: boolean = false;
  selectedManifest: GeminiAnalyzedItem[] | null = null;
  isLoadingUploads: boolean = false;
  isLoadingManifest: boolean = false;
  private pollingSubscription: Subscription | undefined;
  private uploadsToPoll: string[] = [];
  private readonly API_BASE_URL = environment.backendApiUrl;

  // New properties for the upload flow
  readonly MAX_FILE_SIZE_MB = 40; // Max upload limit set to 20MB
  selectedFile: File | null = null;
  filePreviewUrl: SafeResourceUrl | null = null;
  customFileName: string = '';
  isUploading: boolean = false;
  uploadProgress: number = 0;
  uploadStatusMessage: string = '';
  private uploadSubscription: Subscription | null = null;

  constructor(
    private http: HttpClient,
    private authService: AuthService,
    private notificationService: NotificationService,
    private uploadService: UploadService,
    private sanitizer: DomSanitizer
  ) {}

  ngOnInit() {
    this.fetchUploads();
    this.startPolling();
    console.log('Environment Production:', environment.production);
    console.log('Environment Backend API URL:', environment.backendApiUrl);
  }

  ngOnDestroy() {
    this.pollingSubscription?.unsubscribe();
    this.uploadSubscription?.unsubscribe();
  }

  logout() {
    this.authService.logout();
    this.notificationService.showInfo('You have been logged out.');
  }

  private getHeaders(): HttpHeaders {
    const token = this.authService.getToken();
    return new HttpHeaders({
      'Authorization': `Bearer ${token}`,
      'Content-Type': 'application/json'
    });
  }

  // --- New Upload Flow Methods ---

  onFileSelected(event: Event) {
    const input = event.target as HTMLInputElement;
    if (input.files && input.files.length > 0) {
      const file = input.files[0];

      if (file.type !== 'video/mp4' && file.type !== 'video/quicktime') {
        this.notificationService.showError('Invalid file type. Only .mp4 files are accepted.');
        this.clearFileInput(input);
        return;
      }

      // Validate file size
      const maxSizeBytes = this.MAX_FILE_SIZE_MB * 1024 * 1024;
      if (file.size > maxSizeBytes) {
        this.notificationService.showError(`File size exceeds the maximum limit of ${this.MAX_FILE_SIZE_MB}MB.`);
        this.clearFileInput(input);
        return;
      }

      this.selectedFile = file;
      this.customFileName = this.selectedFile.name;
      this.filePreviewUrl = this.sanitizer.bypassSecurityTrustResourceUrl(URL.createObjectURL(this.selectedFile));
    }
  }

  cancelSelection() {
    this.selectedFile = null;
    this.filePreviewUrl = null;
    this.customFileName = '';
    this.isUploading = false;
    this.uploadProgress = 0;
    this.uploadStatusMessage = '';
    this.clearFileInput(document.querySelector('input[type=file]'));
  }

  retryUpload(uploadId: string) {
    const upload = this.uploads.find(u => u.uploadId === uploadId);
    if (!upload) {
      this.notificationService.showError('Could not find the upload to retry.');
      return;
    }

    // Provide immediate UI feedback
    upload.status = 'Pending';
    upload.message = 'Retrying processing...';

    this.uploadService.processUpload(uploadId).pipe(
      catchError(error => {
        console.error(`Retry failed for ${uploadId}:`, error);
        this.notificationService.showError(`Retry failed: ${error.message || 'Unknown error'}`);
        // Revert status on failure
        upload.status = 'Failed';
        upload.message = `Retry failed: ${error.message || 'Unknown error'}`;
        return EMPTY; // Stop the observable chain
      })
    ).subscribe(response => {
      this.notificationService.showSuccess(`Retry initiated for ${upload.videoName}.`);
      upload.status = response.status;
      upload.message = response.message;
      // Ensure this upload is picked up by the poller if it's still processing
      if ((response.status === 'Pending' || response.status === 'Processing') && !this.uploadsToPoll.includes(uploadId)) {
        this.uploadsToPoll.push(uploadId);
      }
    });
  }

  onUpload() {
    if (!this.selectedFile || !this.customFileName) {
      this.notificationService.showError('Please select a file and provide a file name.');
      return;
    }

    this.isUploading = true;
    this.uploadProgress = 0;
    this.uploadStatusMessage = 'Requesting upload URL...';

    let finalFileName = this.customFileName;
    if (!this.customFileName.includes('.')) {
      // Append extension if not present
      const fileExtension = this.selectedFile.type === 'video/quicktime' ? '.mov' : '.mp4';
      finalFileName = `${this.customFileName}${fileExtension}`;
    }

    this.uploadSubscription = this.uploadService.getPresignedUrl(finalFileName, this.selectedFile.type).pipe(
      tap(() => {
        this.uploadStatusMessage = 'Uploading video to secure storage...';
      }),
      switchMap((presignedResponse: PresignedUrlResponse) => {
        if (!this.selectedFile) return EMPTY;
        return this.uploadService.uploadFileToS3(presignedResponse.preSignedUrl, this.selectedFile).pipe(
          tap(event => {
            if (event.type === HttpEventType.UploadProgress) {
              this.uploadProgress = Math.round(100 * event.loaded / (event.total || 1));
            }
          }),
          switchMap(event => {
            if (event.type === HttpEventType.Response) {
              this.uploadProgress = 100;
              this.uploadStatusMessage = 'Finalizing upload...';
              return this.uploadService.processUpload(presignedResponse.uploadId);
            }
            return EMPTY;
          })
        );
      }),
      catchError(error => {
        console.error('Upload failed:', error);
        this.notificationService.showError(`Upload failed: ${error.message || 'Unknown error'}`);
        this.isUploading = false;
        return EMPTY;
      }),
      finalize(() => {
        this.isUploading = false;
      })
    ).subscribe({
      next: (processResponse) => {
        this.notificationService.showSuccess('Upload successful! Your video is now being processed.');
        this.cancelSelection();
        this.fetchUploads(); // Refresh the list
      },
      error: (err) => {
        // This block is for safety, but catchError should handle it.
        this.notificationService.showError('An unexpected error occurred during the upload process.');
        this.isUploading = false;
      }
    });
  }

  private clearFileInput(input: HTMLInputElement | null) {
    if (input) {
      input.value = '';
    }
  }


  // --- Existing Methods for Fetching and Polling ---

  fetchUploads() {
    this.isLoadingUploads = true;
    this.http.get<SurveyUpload[]>(`${this.API_BASE_URL}/uploads/user`, { headers: this.getHeaders() })
      .pipe(catchError(() => {
        this.notificationService.showError('Failed to fetch uploads.');
        return of([]);
      }))
      .subscribe((apiUploads) => {
        this.uploadsToPoll = [];
        this.uploads = apiUploads.map(apiUpload => {
          const id = apiUpload.uploadId;
          const shortId = id.length > 8 ? `${id.slice(0, 4)}...${id.slice(-4)}` : id;
          if (apiUpload.status === 'Pending' || apiUpload.status === 'Processing' || apiUpload.status === 'Queued') {
            this.uploadsToPoll.push(apiUpload.uploadId);
          }
          return {
            ...apiUpload,
            progress: (apiUpload.status === 'Completed' || apiUpload.status === 'Failed') ? 100 : 0,
            videoName: apiUpload.fileName || `Video_${shortId}.mp4`
          };
        });
        this.isLoadingUploads = false;
      });
  }

  startPolling() {
    this.pollingSubscription = interval(5000).pipe(
      startWith(0),
      tap(() => {
        if (this.uploadsToPoll.length > 0) {
          this.pollUploadsStatus();
        }
      })
    ).subscribe();
  }

  pollUploadsStatus() {
    this.uploadsToPoll.forEach(uploadId => {
      this.http.get<SurveyUpload>(`${this.API_BASE_URL}/survey/upload/status/${uploadId}`, { headers: this.getHeaders() })
        .pipe(catchError(() => of(null)))
        .subscribe(apiUpload => {
          if (apiUpload) {
            const localUpload = this.uploads.find(u => u.uploadId === apiUpload.uploadId);
            if (localUpload && localUpload.status !== apiUpload.status) {
              localUpload.status = apiUpload.status;
              localUpload.message = apiUpload.message;
              if (apiUpload.status === 'Completed' || apiUpload.status === 'Failed') {
                this.uploadsToPoll = this.uploadsToPoll.filter(id => id !== uploadId);
                this.notificationService.showInfo(`Upload status for ${apiUpload.fileName} is now ${apiUpload.status}.`);
              }
            }
          }
        });
    });
  }

  getStatusClass(status: string): string {
    switch (status) {
      case 'Pending': return 'status-pending';
      case 'Processing': return 'status-processing';
      case 'Queued': return 'status-queued';
      case 'Completed': return ''; // No status badge for completed, as per new requirement
      case 'Failed': return 'status-failed';
      default: return '';
    }
  }

  openDigitalManifest(uploadId: string) {
    this.isLoadingManifest = true;
    this.http.get<GeminiAnalyzedItem[]>(`${this.API_BASE_URL}/uploads/${uploadId}/analysis`, { headers: this.getHeaders() })
      .pipe(catchError(() => {
        this.notificationService.showError('Failed to fetch digital manifest.');
        return of(null);
      }))
      .subscribe((manifest) => {
        if (manifest) {
          this.selectedManifest = manifest;
          this.isModalOpen = true;
        }
        this.isLoadingManifest = false;
      });
  }

  closeDigitalManifest() {
    this.isModalOpen = false;
    this.selectedManifest = null;
  }
}
<div class="dashboard-container">
  <!-- Header -->
  <header class="dashboard-header">
    <div class="logo"></div>
    <div class="user-profile">
      <img />
      <button class="logout-button" (click)="logout()">Logout</button>
    </div>
  </header>

  <!-- Main Content -->
  <main class="dashboard-main">
    <h2 class="video-survey-header">
      Video Survey
    </h2>
    <p class="dashboard-description">
      Upload a video of your household items to generate a comprehensive <b>digital manifest</b>.
      <br>
      Simply select a video file or record directly from your device.
    </p>

    <!-- Upload Options Area -->
    <div class="upload-options-area">
      <div class="upload-option" (click)="fileUploadInput.click()">
        <input
          type="file"
          #fileUploadInput
          (change)="onFileSelected($event)"
          hidden
          accept="video/*"
        />
        <p>Upload a video file</p>
        <p class="small-text">Only small files less than {{this.MAX_FILE_SIZE_MB}} MB are supported</p>
      </div>

      <div class="upload-option" (click)="cameraInput.click()">
        <input
          type="file"
          #cameraInput
          (change)="onFileSelected($event)"
          hidden
          accept="video/*"
          capture="environment"
        />
        <p>Record directly</p>
        <p class="small-text">Set your camera settings to a lower resolution (30 FPS, 480p-720p)</p>
      </div>
    </div>

    <!-- New Upload Preview and Confirmation Section -->
    <div *ngIf="selectedFile" class="upload-preview-container">
      <h4 class="preview-header">Upload Confirmation</h4>
      <div class="preview-content">
        <div class="video-preview">
          <video [src]="filePreviewUrl" controls></video>
        </div>
        <div class="upload-form">
          <div class="form-group">
            <label for="customFileName">File Name</label>
            <input
              id="customFileName"
              type="text"
              [(ngModel)]="customFileName"
              placeholder="Enter a custom name for your video"
              [disabled]="isUploading"
            />
          </div>
          <div class="upload-actions">
            <button
              class="action-button primary-button"
              (click)="onUpload()"
              [disabled]="isUploading || !customFileName"
            >
              {{ isUploading ? 'Uploading...' : 'Confirm & Upload' }}
            </button>
            <button
              class="action-button cancel-button"
              (click)="cancelSelection()"
              [disabled]="isUploading"
            >
              Cancel
            </button>
          </div>
        </div>
      </div>
      <!-- Upload Status with Spinner -->
      <div *ngIf="isUploading" class="upload-progress-section">
        <p class="status-message">
          {{ uploadStatusMessage }}
          <span class="inline-spinner text-primary" role="status" aria-hidden="true"></span>
        </p>
      </div>
    </div>

    <!-- Survey List -->
    <div class="survey-list">
      <h3>Recent Uploads</h3>
      <div *ngIf="isLoadingUploads" class="loading-spinner-container">
        <div class="spinner-border text-primary" role="status">
          <span class="visually-hidden">Loading uploads...</span>
        </div>
        <p>Loading uploads...</p>
      </div>
      <ng-container *ngIf="!isLoadingUploads">
        <div class="upload-item-card" *ngFor="let upload of uploads">
          <div class="item-details">
            <span class="video-name">{{ upload.fileName || upload.videoName }}</span>
            <span class="timestamp">{{ upload.createdTimestamp | date: 'short' }}</span>
          </div>
          <div class="item-status">
            <span
              *ngIf="upload.status !== 'Completed'"
              class="status-badge"
              [ngClass]="getStatusClass(upload.status)"
            >
              {{ upload.status }}
              <span
                *ngIf="upload.status === 'Pending' || upload.status === 'Processing' || upload.status === 'Queued'"
                class="inline-spinner text-primary"
                role="status"
                aria-hidden="true"
              ></span>
            </span>
          </div>
          <div class="item-actions">
            <button
              *ngIf="upload.status === 'Completed'"
              class="action-button primary-button"
              (click)="openDigitalManifest(upload.uploadId)"
            >
              Get Digital Manifest
            </button>
            <button
              *ngIf="upload.status === 'Failed'"
              class="action-button retry-button"
              (click)="retryUpload(upload.uploadId)"
            >
              Retry
            </button>
          </div>
        </div>
        <p *ngIf="uploads.length === 0" class="no-uploads">No uploads yet.</p>
      </ng-container>
    </div>
  </main>
</div>

<!-- Digital Manifest Modal -->
<app-digital-manifest-modal
  *ngIf="isModalOpen"
  [manifestData]="selectedManifest"
  [isLoading]="isLoadingManifest"
  (closeModal)="closeDigitalManifest()"
>
</app-digital-manifest-modal>
